# Generated by Django 3.1.8 on 2021-07-26 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20201201_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='remote_urls',
            field=models.JSONField(default=dict, help_text='This will keep any url'),
        ),
        migrations.AddField(
            model_name='media',
            name='remote_urls',
            field=models.JSONField(default=dict, help_text='This will keep any url'),
        ),
    ]
